# permissions for end users to edit alicloudclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alicloudcluster-editor-role
rules:
- apiGroups:
  - cluster.cloudplus.io
  resources:
  - alicloudclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.cloudplus.io
  resources:
  - alicloudclusters/status
  verbs:
  - get
